SET SERVEROUTPUT ON;
DECLARE
  P_I_FECHA_HORA TIMESTAMP;
  P_I_TIME_ZONE VARCHAR2(200);
  P_O_FECHA_LOCAL VARCHAR2(200);
  P_O_HORA_LOCAL VARCHAR2(200);
BEGIN
  P_I_FECHA_HORA := SYSTIMESTAMP;
  P_I_TIME_ZONE := '+13:00';

  FORMATO_UTC_A_LOCAL(
    P_I_FECHA_HORA,
    P_I_TIME_ZONE,
    P_O_FECHA_LOCAL,
    P_O_HORA_LOCAL
  );
DBMS_OUTPUT.PUT_LINE('P_O_FECHA_LOCAL = ' || P_O_FECHA_LOCAL);
  
  
DBMS_OUTPUT.PUT_LINE('P_O_HORA_LOCAL = ' || P_O_HORA_LOCAL);

END;
