SET SERVEROUTPUT ON;
DECLARE
  P_NRO_EXAMEN NUMBER;
  P_NRO_ESTUDIANTE NUMBER;
  P_FECHA DATE;
  P_NOMBRE_INSTITUCION VARCHAR2(200);
  P_NRO_SALON NUMBER;
  P_NRO_SILLA NUMBER;
  P_STATUS NUMBER;
BEGIN
  P_NRO_EXAMEN := 1;
  P_NRO_ESTUDIANTE := 1;
  P_FECHA := TO_DATE('02/03/11', 'DD/MM/RR');
  P_NOMBRE_INSTITUCION := NULL;

  BUSCAR_ULTIMO_SALON_SILLA(
    P_NRO_EXAMEN,
    P_NRO_ESTUDIANTE,
    P_FECHA,
    P_NOMBRE_INSTITUCION,
    P_NRO_SALON ,
    P_NRO_SILLA,
    P_STATUS
  );
 
DBMS_OUTPUT.PUT_LINE('P_NOMBRE_INSTITUCION = ' || P_NOMBRE_INSTITUCION);

 
DBMS_OUTPUT.PUT_LINE('P_NRO_SALON = ' || P_NRO_SALON);

DBMS_OUTPUT.PUT_LINE('P_NRO_SILLA = ' || P_NRO_SILLA);

DBMS_OUTPUT.PUT_LINE('P_STATUS = ' || P_STATUS);

END;
